[package]
name = "bin-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
num-traits = "0.2.18"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
num-bigint-dig = { version = "0.8.4", features = ["prime"] }

[dev-dependencies]
criterion = "0.5.1"

[features]
interactive_mp = []
non_interactive_mp = []

[[bench]]
name = "ntt"
harness = false

[[bench]]
name = "modulus"
harness = false

[[example]]
name = "interactive_fheuint8"
path = "./examples/interactive_fheuint8.rs"

[[example]]
name = "non_interactive_fheuint8"
path = "./examples/non_interactive_fheuint8.rs"
required-features = ["non_interactive_mp"]


[[example]]
name = "meeting_friends"
path = "./examples/meeting_friends.rs"
required-features = ["non_interactive_mp"]